package cn.edu.xmu.oomall.activity.model.po;

import java.time.LocalDateTime;

public class AdvanceSalePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.pay_time
     *
     * @mbg.generated
     */
    private LocalDateTime payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.advance_pay_price
     *
     * @mbg.generated
     */
    private Long advancePayPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.online_by
     *
     * @mbg.generated
     */
    private Long onlineBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.online_time
     *
     * @mbg.generated
     */
    private LocalDateTime onlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.online_name
     *
     * @mbg.generated
     */
    private String onlineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.offline_by
     *
     * @mbg.generated
     */
    private Long offlineBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.offline_time
     *
     * @mbg.generated
     */
    private LocalDateTime offlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_advance_sale.offline_name
     *
     * @mbg.generated
     */
    private String offlineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.id
     *
     * @return the value of oomall_advance_sale.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.id
     *
     * @param id the value for oomall_advance_sale.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.shop_id
     *
     * @return the value of oomall_advance_sale.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.shop_id
     *
     * @param shopId the value for oomall_advance_sale.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.shop_name
     *
     * @return the value of oomall_advance_sale.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.shop_name
     *
     * @param shopName the value for oomall_advance_sale.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.name
     *
     * @return the value of oomall_advance_sale.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.name
     *
     * @param name the value for oomall_advance_sale.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.pay_time
     *
     * @return the value of oomall_advance_sale.pay_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.pay_time
     *
     * @param payTime the value for oomall_advance_sale.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(LocalDateTime payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.advance_pay_price
     *
     * @return the value of oomall_advance_sale.advance_pay_price
     *
     * @mbg.generated
     */
    public Long getAdvancePayPrice() {
        return advancePayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.advance_pay_price
     *
     * @param advancePayPrice the value for oomall_advance_sale.advance_pay_price
     *
     * @mbg.generated
     */
    public void setAdvancePayPrice(Long advancePayPrice) {
        this.advancePayPrice = advancePayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.created_by
     *
     * @return the value of oomall_advance_sale.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.created_by
     *
     * @param createdBy the value for oomall_advance_sale.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.create_name
     *
     * @return the value of oomall_advance_sale.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.create_name
     *
     * @param createName the value for oomall_advance_sale.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.create_time
     *
     * @return the value of oomall_advance_sale.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.create_time
     *
     * @param createTime the value for oomall_advance_sale.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.online_by
     *
     * @return the value of oomall_advance_sale.online_by
     *
     * @mbg.generated
     */
    public Long getOnlineBy() {
        return onlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.online_by
     *
     * @param onlineBy the value for oomall_advance_sale.online_by
     *
     * @mbg.generated
     */
    public void setOnlineBy(Long onlineBy) {
        this.onlineBy = onlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.online_time
     *
     * @return the value of oomall_advance_sale.online_time
     *
     * @mbg.generated
     */
    public LocalDateTime getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.online_time
     *
     * @param onlineTime the value for oomall_advance_sale.online_time
     *
     * @mbg.generated
     */
    public void setOnlineTime(LocalDateTime onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.online_name
     *
     * @return the value of oomall_advance_sale.online_name
     *
     * @mbg.generated
     */
    public String getOnlineName() {
        return onlineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.online_name
     *
     * @param onlineName the value for oomall_advance_sale.online_name
     *
     * @mbg.generated
     */
    public void setOnlineName(String onlineName) {
        this.onlineName = onlineName == null ? null : onlineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.offline_by
     *
     * @return the value of oomall_advance_sale.offline_by
     *
     * @mbg.generated
     */
    public Long getOfflineBy() {
        return offlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.offline_by
     *
     * @param offlineBy the value for oomall_advance_sale.offline_by
     *
     * @mbg.generated
     */
    public void setOfflineBy(Long offlineBy) {
        this.offlineBy = offlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.offline_time
     *
     * @return the value of oomall_advance_sale.offline_time
     *
     * @mbg.generated
     */
    public LocalDateTime getOfflineTime() {
        return offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.offline_time
     *
     * @param offlineTime the value for oomall_advance_sale.offline_time
     *
     * @mbg.generated
     */
    public void setOfflineTime(LocalDateTime offlineTime) {
        this.offlineTime = offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_advance_sale.offline_name
     *
     * @return the value of oomall_advance_sale.offline_name
     *
     * @mbg.generated
     */
    public String getOfflineName() {
        return offlineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_advance_sale.offline_name
     *
     * @param offlineName the value for oomall_advance_sale.offline_name
     *
     * @mbg.generated
     */
    public void setOfflineName(String offlineName) {
        this.offlineName = offlineName == null ? null : offlineName.trim();
    }
}