package cn.edu.xmu.oomall.goods.mapper;

import cn.edu.xmu.oomall.goods.model.po.OnSalePo;
import cn.edu.xmu.oomall.goods.model.po.OnSalePoExample;
import java.util.List;

public interface OnSalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int insert(OnSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int insertSelective(OnSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    List<OnSalePo> selectByExample(OnSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    OnSalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OnSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OnSalePo record);
}