package cn.edu.xmu.oomall.orders.model.po;

import java.time.LocalDateTime;

public class OrderItemPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.sub_order_id
     *
     * @mbg.generated
     */
    private Long subOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.onsale_id
     *
     * @mbg.generated
     */
    private Long onsaleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.column_12
     *
     * @mbg.generated
     */
    private Integer column12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.quantity
     *
     * @mbg.generated
     */
    private Long quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.modified_by
     *
     * @mbg.generated
     */
    private Long modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.modi_name
     *
     * @mbg.generated
     */
    private String modiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.discount_price
     *
     * @mbg.generated
     */
    private Long discountPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.point
     *
     * @mbg.generated
     */
    private Long point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.coupon_activity_id
     *
     * @mbg.generated
     */
    private Long couponActivityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_order_item.coupon_id
     *
     * @mbg.generated
     */
    private Long couponId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.id
     *
     * @return the value of oomall_order_item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.id
     *
     * @param id the value for oomall_order_item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.order_id
     *
     * @return the value of oomall_order_item.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.order_id
     *
     * @param orderId the value for oomall_order_item.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.sub_order_id
     *
     * @return the value of oomall_order_item.sub_order_id
     *
     * @mbg.generated
     */
    public Long getSubOrderId() {
        return subOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.sub_order_id
     *
     * @param subOrderId the value for oomall_order_item.sub_order_id
     *
     * @mbg.generated
     */
    public void setSubOrderId(Long subOrderId) {
        this.subOrderId = subOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.product_id
     *
     * @return the value of oomall_order_item.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.product_id
     *
     * @param productId the value for oomall_order_item.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.onsale_id
     *
     * @return the value of oomall_order_item.onsale_id
     *
     * @mbg.generated
     */
    public Long getOnsaleId() {
        return onsaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.onsale_id
     *
     * @param onsaleId the value for oomall_order_item.onsale_id
     *
     * @mbg.generated
     */
    public void setOnsaleId(Long onsaleId) {
        this.onsaleId = onsaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.column_12
     *
     * @return the value of oomall_order_item.column_12
     *
     * @mbg.generated
     */
    public Integer getColumn12() {
        return column12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.column_12
     *
     * @param column12 the value for oomall_order_item.column_12
     *
     * @mbg.generated
     */
    public void setColumn12(Integer column12) {
        this.column12 = column12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.quantity
     *
     * @return the value of oomall_order_item.quantity
     *
     * @mbg.generated
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.quantity
     *
     * @param quantity the value for oomall_order_item.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.create_by
     *
     * @return the value of oomall_order_item.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.create_by
     *
     * @param createBy the value for oomall_order_item.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.create_name
     *
     * @return the value of oomall_order_item.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.create_name
     *
     * @param createName the value for oomall_order_item.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.modified_by
     *
     * @return the value of oomall_order_item.modified_by
     *
     * @mbg.generated
     */
    public Long getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.modified_by
     *
     * @param modifiedBy the value for oomall_order_item.modified_by
     *
     * @mbg.generated
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.modi_name
     *
     * @return the value of oomall_order_item.modi_name
     *
     * @mbg.generated
     */
    public String getModiName() {
        return modiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.modi_name
     *
     * @param modiName the value for oomall_order_item.modi_name
     *
     * @mbg.generated
     */
    public void setModiName(String modiName) {
        this.modiName = modiName == null ? null : modiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.gmt_create
     *
     * @return the value of oomall_order_item.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.gmt_create
     *
     * @param gmtCreate the value for oomall_order_item.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.gmt_modified
     *
     * @return the value of oomall_order_item.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.gmt_modified
     *
     * @param gmtModified the value for oomall_order_item.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.price
     *
     * @return the value of oomall_order_item.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.price
     *
     * @param price the value for oomall_order_item.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.discount_price
     *
     * @return the value of oomall_order_item.discount_price
     *
     * @mbg.generated
     */
    public Long getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.discount_price
     *
     * @param discountPrice the value for oomall_order_item.discount_price
     *
     * @mbg.generated
     */
    public void setDiscountPrice(Long discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.point
     *
     * @return the value of oomall_order_item.point
     *
     * @mbg.generated
     */
    public Long getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.point
     *
     * @param point the value for oomall_order_item.point
     *
     * @mbg.generated
     */
    public void setPoint(Long point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.name
     *
     * @return the value of oomall_order_item.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.name
     *
     * @param name the value for oomall_order_item.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.coupon_activity_id
     *
     * @return the value of oomall_order_item.coupon_activity_id
     *
     * @mbg.generated
     */
    public Long getCouponActivityId() {
        return couponActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.coupon_activity_id
     *
     * @param couponActivityId the value for oomall_order_item.coupon_activity_id
     *
     * @mbg.generated
     */
    public void setCouponActivityId(Long couponActivityId) {
        this.couponActivityId = couponActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_order_item.coupon_id
     *
     * @return the value of oomall_order_item.coupon_id
     *
     * @mbg.generated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_order_item.coupon_id
     *
     * @param couponId the value for oomall_order_item.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }
}