package cn.edu.xmu.oomall.shop.model.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ShopPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public ShopPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDepositIsNull() {
            addCriterion("`deposit` is null");
            return (Criteria) this;
        }

        public Criteria andDepositIsNotNull() {
            addCriterion("`deposit` is not null");
            return (Criteria) this;
        }

        public Criteria andDepositEqualTo(Long value) {
            addCriterion("`deposit` =", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotEqualTo(Long value) {
            addCriterion("`deposit` <>", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThan(Long value) {
            addCriterion("`deposit` >", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThanOrEqualTo(Long value) {
            addCriterion("`deposit` >=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThan(Long value) {
            addCriterion("`deposit` <", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThanOrEqualTo(Long value) {
            addCriterion("`deposit` <=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositIn(List<Long> values) {
            addCriterion("`deposit` in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotIn(List<Long> values) {
            addCriterion("`deposit` not in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositBetween(Long value1, Long value2) {
            addCriterion("`deposit` between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotBetween(Long value1, Long value2) {
            addCriterion("`deposit` not between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdIsNull() {
            addCriterion("`deposit_threshold` is null");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdIsNotNull() {
            addCriterion("`deposit_threshold` is not null");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdEqualTo(Long value) {
            addCriterion("`deposit_threshold` =", value, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdNotEqualTo(Long value) {
            addCriterion("`deposit_threshold` <>", value, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdGreaterThan(Long value) {
            addCriterion("`deposit_threshold` >", value, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdGreaterThanOrEqualTo(Long value) {
            addCriterion("`deposit_threshold` >=", value, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdLessThan(Long value) {
            addCriterion("`deposit_threshold` <", value, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdLessThanOrEqualTo(Long value) {
            addCriterion("`deposit_threshold` <=", value, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdIn(List<Long> values) {
            addCriterion("`deposit_threshold` in", values, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdNotIn(List<Long> values) {
            addCriterion("`deposit_threshold` not in", values, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdBetween(Long value1, Long value2) {
            addCriterion("`deposit_threshold` between", value1, value2, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andDepositThresholdNotBetween(Long value1, Long value2) {
            addCriterion("`deposit_threshold` not between", value1, value2, "depositThreshold");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("`created_by` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("`created_by` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("`created_by` =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("`created_by` <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("`created_by` >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("`created_by` >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("`created_by` <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("`created_by` <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("`created_by` in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("`created_by` not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("`created_by` between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("`created_by` not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("`create_name` is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("`create_name` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("`create_name` =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("`create_name` <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("`create_name` >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("`create_name` >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("`create_name` <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("`create_name` <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("`create_name` like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("`create_name` not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("`create_name` in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("`create_name` not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("`create_name` between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("`create_name` not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOnlineByIsNull() {
            addCriterion("`online_by` is null");
            return (Criteria) this;
        }

        public Criteria andOnlineByIsNotNull() {
            addCriterion("`online_by` is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineByEqualTo(Long value) {
            addCriterion("`online_by` =", value, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByNotEqualTo(Long value) {
            addCriterion("`online_by` <>", value, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByGreaterThan(Long value) {
            addCriterion("`online_by` >", value, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByGreaterThanOrEqualTo(Long value) {
            addCriterion("`online_by` >=", value, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByLessThan(Long value) {
            addCriterion("`online_by` <", value, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByLessThanOrEqualTo(Long value) {
            addCriterion("`online_by` <=", value, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByIn(List<Long> values) {
            addCriterion("`online_by` in", values, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByNotIn(List<Long> values) {
            addCriterion("`online_by` not in", values, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByBetween(Long value1, Long value2) {
            addCriterion("`online_by` between", value1, value2, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineByNotBetween(Long value1, Long value2) {
            addCriterion("`online_by` not between", value1, value2, "onlineBy");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeIsNull() {
            addCriterion("`online_time` is null");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeIsNotNull() {
            addCriterion("`online_time` is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeEqualTo(LocalDateTime value) {
            addCriterion("`online_time` =", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`online_time` <>", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeGreaterThan(LocalDateTime value) {
            addCriterion("`online_time` >", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`online_time` >=", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeLessThan(LocalDateTime value) {
            addCriterion("`online_time` <", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`online_time` <=", value, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeIn(List<LocalDateTime> values) {
            addCriterion("`online_time` in", values, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`online_time` not in", values, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`online_time` between", value1, value2, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`online_time` not between", value1, value2, "onlineTime");
            return (Criteria) this;
        }

        public Criteria andOnlineNameIsNull() {
            addCriterion("`online_name` is null");
            return (Criteria) this;
        }

        public Criteria andOnlineNameIsNotNull() {
            addCriterion("`online_name` is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineNameEqualTo(String value) {
            addCriterion("`online_name` =", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameNotEqualTo(String value) {
            addCriterion("`online_name` <>", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameGreaterThan(String value) {
            addCriterion("`online_name` >", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameGreaterThanOrEqualTo(String value) {
            addCriterion("`online_name` >=", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameLessThan(String value) {
            addCriterion("`online_name` <", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameLessThanOrEqualTo(String value) {
            addCriterion("`online_name` <=", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameLike(String value) {
            addCriterion("`online_name` like", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameNotLike(String value) {
            addCriterion("`online_name` not like", value, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameIn(List<String> values) {
            addCriterion("`online_name` in", values, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameNotIn(List<String> values) {
            addCriterion("`online_name` not in", values, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameBetween(String value1, String value2) {
            addCriterion("`online_name` between", value1, value2, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOnlineNameNotBetween(String value1, String value2) {
            addCriterion("`online_name` not between", value1, value2, "onlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineByIsNull() {
            addCriterion("`offline_by` is null");
            return (Criteria) this;
        }

        public Criteria andOfflineByIsNotNull() {
            addCriterion("`offline_by` is not null");
            return (Criteria) this;
        }

        public Criteria andOfflineByEqualTo(Long value) {
            addCriterion("`offline_by` =", value, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByNotEqualTo(Long value) {
            addCriterion("`offline_by` <>", value, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByGreaterThan(Long value) {
            addCriterion("`offline_by` >", value, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByGreaterThanOrEqualTo(Long value) {
            addCriterion("`offline_by` >=", value, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByLessThan(Long value) {
            addCriterion("`offline_by` <", value, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByLessThanOrEqualTo(Long value) {
            addCriterion("`offline_by` <=", value, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByIn(List<Long> values) {
            addCriterion("`offline_by` in", values, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByNotIn(List<Long> values) {
            addCriterion("`offline_by` not in", values, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByBetween(Long value1, Long value2) {
            addCriterion("`offline_by` between", value1, value2, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineByNotBetween(Long value1, Long value2) {
            addCriterion("`offline_by` not between", value1, value2, "offlineBy");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeIsNull() {
            addCriterion("`offline_time` is null");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeIsNotNull() {
            addCriterion("`offline_time` is not null");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeEqualTo(LocalDateTime value) {
            addCriterion("`offline_time` =", value, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`offline_time` <>", value, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeGreaterThan(LocalDateTime value) {
            addCriterion("`offline_time` >", value, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`offline_time` >=", value, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeLessThan(LocalDateTime value) {
            addCriterion("`offline_time` <", value, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`offline_time` <=", value, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeIn(List<LocalDateTime> values) {
            addCriterion("`offline_time` in", values, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`offline_time` not in", values, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`offline_time` between", value1, value2, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`offline_time` not between", value1, value2, "offlineTime");
            return (Criteria) this;
        }

        public Criteria andOfflineNameIsNull() {
            addCriterion("`offline_name` is null");
            return (Criteria) this;
        }

        public Criteria andOfflineNameIsNotNull() {
            addCriterion("`offline_name` is not null");
            return (Criteria) this;
        }

        public Criteria andOfflineNameEqualTo(String value) {
            addCriterion("`offline_name` =", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameNotEqualTo(String value) {
            addCriterion("`offline_name` <>", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameGreaterThan(String value) {
            addCriterion("`offline_name` >", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameGreaterThanOrEqualTo(String value) {
            addCriterion("`offline_name` >=", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameLessThan(String value) {
            addCriterion("`offline_name` <", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameLessThanOrEqualTo(String value) {
            addCriterion("`offline_name` <=", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameLike(String value) {
            addCriterion("`offline_name` like", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameNotLike(String value) {
            addCriterion("`offline_name` not like", value, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameIn(List<String> values) {
            addCriterion("`offline_name` in", values, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameNotIn(List<String> values) {
            addCriterion("`offline_name` not in", values, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameBetween(String value1, String value2) {
            addCriterion("`offline_name` between", value1, value2, "offlineName");
            return (Criteria) this;
        }

        public Criteria andOfflineNameNotBetween(String value1, String value2) {
            addCriterion("`offline_name` not between", value1, value2, "offlineName");
            return (Criteria) this;
        }

        public Criteria andClosedByIsNull() {
            addCriterion("`closed_by` is null");
            return (Criteria) this;
        }

        public Criteria andClosedByIsNotNull() {
            addCriterion("`closed_by` is not null");
            return (Criteria) this;
        }

        public Criteria andClosedByEqualTo(Long value) {
            addCriterion("`closed_by` =", value, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByNotEqualTo(Long value) {
            addCriterion("`closed_by` <>", value, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByGreaterThan(Long value) {
            addCriterion("`closed_by` >", value, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByGreaterThanOrEqualTo(Long value) {
            addCriterion("`closed_by` >=", value, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByLessThan(Long value) {
            addCriterion("`closed_by` <", value, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByLessThanOrEqualTo(Long value) {
            addCriterion("`closed_by` <=", value, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByIn(List<Long> values) {
            addCriterion("`closed_by` in", values, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByNotIn(List<Long> values) {
            addCriterion("`closed_by` not in", values, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByBetween(Long value1, Long value2) {
            addCriterion("`closed_by` between", value1, value2, "closedBy");
            return (Criteria) this;
        }

        public Criteria andClosedByNotBetween(Long value1, Long value2) {
            addCriterion("`closed_by` not between", value1, value2, "closedBy");
            return (Criteria) this;
        }

        public Criteria andCloseTimeIsNull() {
            addCriterion("`close_time` is null");
            return (Criteria) this;
        }

        public Criteria andCloseTimeIsNotNull() {
            addCriterion("`close_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCloseTimeEqualTo(LocalDateTime value) {
            addCriterion("`close_time` =", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`close_time` <>", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeGreaterThan(LocalDateTime value) {
            addCriterion("`close_time` >", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`close_time` >=", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeLessThan(LocalDateTime value) {
            addCriterion("`close_time` <", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`close_time` <=", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeIn(List<LocalDateTime> values) {
            addCriterion("`close_time` in", values, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`close_time` not in", values, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`close_time` between", value1, value2, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`close_time` not between", value1, value2, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseNameIsNull() {
            addCriterion("`close_name` is null");
            return (Criteria) this;
        }

        public Criteria andCloseNameIsNotNull() {
            addCriterion("`close_name` is not null");
            return (Criteria) this;
        }

        public Criteria andCloseNameEqualTo(String value) {
            addCriterion("`close_name` =", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameNotEqualTo(String value) {
            addCriterion("`close_name` <>", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameGreaterThan(String value) {
            addCriterion("`close_name` >", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameGreaterThanOrEqualTo(String value) {
            addCriterion("`close_name` >=", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameLessThan(String value) {
            addCriterion("`close_name` <", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameLessThanOrEqualTo(String value) {
            addCriterion("`close_name` <=", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameLike(String value) {
            addCriterion("`close_name` like", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameNotLike(String value) {
            addCriterion("`close_name` not like", value, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameIn(List<String> values) {
            addCriterion("`close_name` in", values, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameNotIn(List<String> values) {
            addCriterion("`close_name` not in", values, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameBetween(String value1, String value2) {
            addCriterion("`close_name` between", value1, value2, "closeName");
            return (Criteria) this;
        }

        public Criteria andCloseNameNotBetween(String value1, String value2) {
            addCriterion("`close_name` not between", value1, value2, "closeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_shop
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_shop
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}