package cn.edu.xmu.oomall.goods.model.po;

import java.time.LocalDateTime;

public class OnSalePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.begin_time
     *
     * @mbg.generated
     */
    private LocalDateTime beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.share_act_id
     *
     * @mbg.generated
     */
    private Long shareActId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.online_by
     *
     * @mbg.generated
     */
    private Long onlineBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.online_time
     *
     * @mbg.generated
     */
    private LocalDateTime onlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.online_name
     *
     * @mbg.generated
     */
    private String onlineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.offline_by
     *
     * @mbg.generated
     */
    private Long offlineBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.offline_time
     *
     * @mbg.generated
     */
    private LocalDateTime offlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_onsale.offline_name
     *
     * @mbg.generated
     */
    private String offlineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.id
     *
     * @return the value of oomall_onsale.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.id
     *
     * @param id the value for oomall_onsale.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.shop_id
     *
     * @return the value of oomall_onsale.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.shop_id
     *
     * @param shopId the value for oomall_onsale.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.product_id
     *
     * @return the value of oomall_onsale.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.product_id
     *
     * @param productId the value for oomall_onsale.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.price
     *
     * @return the value of oomall_onsale.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.price
     *
     * @param price the value for oomall_onsale.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.begin_time
     *
     * @return the value of oomall_onsale.begin_time
     *
     * @mbg.generated
     */
    public LocalDateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.begin_time
     *
     * @param beginTime the value for oomall_onsale.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.end_time
     *
     * @return the value of oomall_onsale.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.end_time
     *
     * @param endTime the value for oomall_onsale.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.quantity
     *
     * @return the value of oomall_onsale.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.quantity
     *
     * @param quantity the value for oomall_onsale.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.type
     *
     * @return the value of oomall_onsale.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.type
     *
     * @param type the value for oomall_onsale.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.activity_id
     *
     * @return the value of oomall_onsale.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.activity_id
     *
     * @param activityId the value for oomall_onsale.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.share_act_id
     *
     * @return the value of oomall_onsale.share_act_id
     *
     * @mbg.generated
     */
    public Long getShareActId() {
        return shareActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.share_act_id
     *
     * @param shareActId the value for oomall_onsale.share_act_id
     *
     * @mbg.generated
     */
    public void setShareActId(Long shareActId) {
        this.shareActId = shareActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.state
     *
     * @return the value of oomall_onsale.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.state
     *
     * @param state the value for oomall_onsale.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.created_by
     *
     * @return the value of oomall_onsale.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.created_by
     *
     * @param createdBy the value for oomall_onsale.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.create_name
     *
     * @return the value of oomall_onsale.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.create_name
     *
     * @param createName the value for oomall_onsale.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.create_time
     *
     * @return the value of oomall_onsale.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.create_time
     *
     * @param createTime the value for oomall_onsale.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.online_by
     *
     * @return the value of oomall_onsale.online_by
     *
     * @mbg.generated
     */
    public Long getOnlineBy() {
        return onlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.online_by
     *
     * @param onlineBy the value for oomall_onsale.online_by
     *
     * @mbg.generated
     */
    public void setOnlineBy(Long onlineBy) {
        this.onlineBy = onlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.online_time
     *
     * @return the value of oomall_onsale.online_time
     *
     * @mbg.generated
     */
    public LocalDateTime getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.online_time
     *
     * @param onlineTime the value for oomall_onsale.online_time
     *
     * @mbg.generated
     */
    public void setOnlineTime(LocalDateTime onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.online_name
     *
     * @return the value of oomall_onsale.online_name
     *
     * @mbg.generated
     */
    public String getOnlineName() {
        return onlineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.online_name
     *
     * @param onlineName the value for oomall_onsale.online_name
     *
     * @mbg.generated
     */
    public void setOnlineName(String onlineName) {
        this.onlineName = onlineName == null ? null : onlineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.offline_by
     *
     * @return the value of oomall_onsale.offline_by
     *
     * @mbg.generated
     */
    public Long getOfflineBy() {
        return offlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.offline_by
     *
     * @param offlineBy the value for oomall_onsale.offline_by
     *
     * @mbg.generated
     */
    public void setOfflineBy(Long offlineBy) {
        this.offlineBy = offlineBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.offline_time
     *
     * @return the value of oomall_onsale.offline_time
     *
     * @mbg.generated
     */
    public LocalDateTime getOfflineTime() {
        return offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.offline_time
     *
     * @param offlineTime the value for oomall_onsale.offline_time
     *
     * @mbg.generated
     */
    public void setOfflineTime(LocalDateTime offlineTime) {
        this.offlineTime = offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_onsale.offline_name
     *
     * @return the value of oomall_onsale.offline_name
     *
     * @mbg.generated
     */
    public String getOfflineName() {
        return offlineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_onsale.offline_name
     *
     * @param offlineName the value for oomall_onsale.offline_name
     *
     * @mbg.generated
     */
    public void setOfflineName(String offlineName) {
        this.offlineName = offlineName == null ? null : offlineName.trim();
    }
}