package cn.edu.xmu.oomall.goods.model.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ProductPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public ProductPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("`shop_id` is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("`shop_id` is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("`shop_id` =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("`shop_id` <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("`shop_id` >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`shop_id` >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("`shop_id` <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("`shop_id` <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Long> values) {
            addCriterion("`shop_id` in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Long> values) {
            addCriterion("`shop_id` not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("`shop_id` between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("`shop_id` not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("`shop_name` is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("`shop_name` is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("`shop_name` =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("`shop_name` <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("`shop_name` >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("`shop_name` >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("`shop_name` <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("`shop_name` <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("`shop_name` like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("`shop_name` not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("`shop_name` in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("`shop_name` not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("`shop_name` between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("`shop_name` not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("`goods_id` is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("`goods_id` is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Long value) {
            addCriterion("`goods_id` =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Long value) {
            addCriterion("`goods_id` <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Long value) {
            addCriterion("`goods_id` >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`goods_id` >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Long value) {
            addCriterion("`goods_id` <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Long value) {
            addCriterion("`goods_id` <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Long> values) {
            addCriterion("`goods_id` in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Long> values) {
            addCriterion("`goods_id` not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Long value1, Long value2) {
            addCriterion("`goods_id` between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Long value1, Long value2) {
            addCriterion("`goods_id` not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("`category_id` is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("`category_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Long value) {
            addCriterion("`category_id` =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Long value) {
            addCriterion("`category_id` <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Long value) {
            addCriterion("`category_id` >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`category_id` >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Long value) {
            addCriterion("`category_id` <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("`category_id` <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Long> values) {
            addCriterion("`category_id` in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Long> values) {
            addCriterion("`category_id` not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Long value1, Long value2) {
            addCriterion("`category_id` between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("`category_id` not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andFreightIdIsNull() {
            addCriterion("`freight_id` is null");
            return (Criteria) this;
        }

        public Criteria andFreightIdIsNotNull() {
            addCriterion("`freight_id` is not null");
            return (Criteria) this;
        }

        public Criteria andFreightIdEqualTo(Long value) {
            addCriterion("`freight_id` =", value, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdNotEqualTo(Long value) {
            addCriterion("`freight_id` <>", value, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdGreaterThan(Long value) {
            addCriterion("`freight_id` >", value, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`freight_id` >=", value, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdLessThan(Long value) {
            addCriterion("`freight_id` <", value, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdLessThanOrEqualTo(Long value) {
            addCriterion("`freight_id` <=", value, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdIn(List<Long> values) {
            addCriterion("`freight_id` in", values, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdNotIn(List<Long> values) {
            addCriterion("`freight_id` not in", values, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdBetween(Long value1, Long value2) {
            addCriterion("`freight_id` between", value1, value2, "freightId");
            return (Criteria) this;
        }

        public Criteria andFreightIdNotBetween(Long value1, Long value2) {
            addCriterion("`freight_id` not between", value1, value2, "freightId");
            return (Criteria) this;
        }

        public Criteria andSkuSnIsNull() {
            addCriterion("`sku_sn` is null");
            return (Criteria) this;
        }

        public Criteria andSkuSnIsNotNull() {
            addCriterion("`sku_sn` is not null");
            return (Criteria) this;
        }

        public Criteria andSkuSnEqualTo(String value) {
            addCriterion("`sku_sn` =", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnNotEqualTo(String value) {
            addCriterion("`sku_sn` <>", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnGreaterThan(String value) {
            addCriterion("`sku_sn` >", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnGreaterThanOrEqualTo(String value) {
            addCriterion("`sku_sn` >=", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnLessThan(String value) {
            addCriterion("`sku_sn` <", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnLessThanOrEqualTo(String value) {
            addCriterion("`sku_sn` <=", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnLike(String value) {
            addCriterion("`sku_sn` like", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnNotLike(String value) {
            addCriterion("`sku_sn` not like", value, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnIn(List<String> values) {
            addCriterion("`sku_sn` in", values, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnNotIn(List<String> values) {
            addCriterion("`sku_sn` not in", values, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnBetween(String value1, String value2) {
            addCriterion("`sku_sn` between", value1, value2, "skuSn");
            return (Criteria) this;
        }

        public Criteria andSkuSnNotBetween(String value1, String value2) {
            addCriterion("`sku_sn` not between", value1, value2, "skuSn");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNull() {
            addCriterion("`original_price` is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNotNull() {
            addCriterion("`original_price` is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceEqualTo(Long value) {
            addCriterion("`original_price` =", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotEqualTo(Long value) {
            addCriterion("`original_price` <>", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThan(Long value) {
            addCriterion("`original_price` >", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("`original_price` >=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThan(Long value) {
            addCriterion("`original_price` <", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThanOrEqualTo(Long value) {
            addCriterion("`original_price` <=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIn(List<Long> values) {
            addCriterion("`original_price` in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotIn(List<Long> values) {
            addCriterion("`original_price` not in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceBetween(Long value1, Long value2) {
            addCriterion("`original_price` between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotBetween(Long value1, Long value2) {
            addCriterion("`original_price` not between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("`weight` is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("`weight` is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Long value) {
            addCriterion("`weight` =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Long value) {
            addCriterion("`weight` <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Long value) {
            addCriterion("`weight` >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Long value) {
            addCriterion("`weight` >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Long value) {
            addCriterion("`weight` <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Long value) {
            addCriterion("`weight` <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Long> values) {
            addCriterion("`weight` in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Long> values) {
            addCriterion("`weight` not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Long value1, Long value2) {
            addCriterion("`weight` between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Long value1, Long value2) {
            addCriterion("`weight` not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNull() {
            addCriterion("`image_url` is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNotNull() {
            addCriterion("`image_url` is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlEqualTo(String value) {
            addCriterion("`image_url` =", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotEqualTo(String value) {
            addCriterion("`image_url` <>", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThan(String value) {
            addCriterion("`image_url` >", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("`image_url` >=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThan(String value) {
            addCriterion("`image_url` <", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThanOrEqualTo(String value) {
            addCriterion("`image_url` <=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLike(String value) {
            addCriterion("`image_url` like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotLike(String value) {
            addCriterion("`image_url` not like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIn(List<String> values) {
            addCriterion("`image_url` in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotIn(List<String> values) {
            addCriterion("`image_url` not in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlBetween(String value1, String value2) {
            addCriterion("`image_url` between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotBetween(String value1, String value2) {
            addCriterion("`image_url` not between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeIsNull() {
            addCriterion("`barcode` is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeIsNotNull() {
            addCriterion("`barcode` is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeEqualTo(String value) {
            addCriterion("`barcode` =", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotEqualTo(String value) {
            addCriterion("`barcode` <>", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThan(String value) {
            addCriterion("`barcode` >", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("`barcode` >=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThan(String value) {
            addCriterion("`barcode` <", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThanOrEqualTo(String value) {
            addCriterion("`barcode` <=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLike(String value) {
            addCriterion("`barcode` like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotLike(String value) {
            addCriterion("`barcode` not like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeIn(List<String> values) {
            addCriterion("`barcode` in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotIn(List<String> values) {
            addCriterion("`barcode` not in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeBetween(String value1, String value2) {
            addCriterion("`barcode` between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotBetween(String value1, String value2) {
            addCriterion("`barcode` not between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("`unit` is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("`unit` is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("`unit` =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("`unit` <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("`unit` >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("`unit` >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("`unit` <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("`unit` <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("`unit` like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("`unit` not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("`unit` in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("`unit` not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("`unit` between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("`unit` not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceIsNull() {
            addCriterion("`origin_place` is null");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceIsNotNull() {
            addCriterion("`origin_place` is not null");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceEqualTo(String value) {
            addCriterion("`origin_place` =", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceNotEqualTo(String value) {
            addCriterion("`origin_place` <>", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceGreaterThan(String value) {
            addCriterion("`origin_place` >", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("`origin_place` >=", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceLessThan(String value) {
            addCriterion("`origin_place` <", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceLessThanOrEqualTo(String value) {
            addCriterion("`origin_place` <=", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceLike(String value) {
            addCriterion("`origin_place` like", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceNotLike(String value) {
            addCriterion("`origin_place` not like", value, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceIn(List<String> values) {
            addCriterion("`origin_place` in", values, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceNotIn(List<String> values) {
            addCriterion("`origin_place` not in", values, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceBetween(String value1, String value2) {
            addCriterion("`origin_place` between", value1, value2, "originPlace");
            return (Criteria) this;
        }

        public Criteria andOriginPlaceNotBetween(String value1, String value2) {
            addCriterion("`origin_place` not between", value1, value2, "originPlace");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("`create_name` is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("`create_name` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("`create_name` =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("`create_name` <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("`create_name` >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("`create_name` >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("`create_name` <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("`create_name` <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("`create_name` like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("`create_name` not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("`create_name` in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("`create_name` not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("`create_name` between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("`create_name` not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andAuditedByIsNull() {
            addCriterion("`audited_by` is null");
            return (Criteria) this;
        }

        public Criteria andAuditedByIsNotNull() {
            addCriterion("`audited_by` is not null");
            return (Criteria) this;
        }

        public Criteria andAuditedByEqualTo(Long value) {
            addCriterion("`audited_by` =", value, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByNotEqualTo(Long value) {
            addCriterion("`audited_by` <>", value, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByGreaterThan(Long value) {
            addCriterion("`audited_by` >", value, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByGreaterThanOrEqualTo(Long value) {
            addCriterion("`audited_by` >=", value, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByLessThan(Long value) {
            addCriterion("`audited_by` <", value, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByLessThanOrEqualTo(Long value) {
            addCriterion("`audited_by` <=", value, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByIn(List<Long> values) {
            addCriterion("`audited_by` in", values, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByNotIn(List<Long> values) {
            addCriterion("`audited_by` not in", values, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByBetween(Long value1, Long value2) {
            addCriterion("`audited_by` between", value1, value2, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditedByNotBetween(Long value1, Long value2) {
            addCriterion("`audited_by` not between", value1, value2, "auditedBy");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("`audit_time` is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("`audit_time` is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(LocalDateTime value) {
            addCriterion("`audit_time` =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`audit_time` <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(LocalDateTime value) {
            addCriterion("`audit_time` >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`audit_time` >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(LocalDateTime value) {
            addCriterion("`audit_time` <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`audit_time` <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<LocalDateTime> values) {
            addCriterion("`audit_time` in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`audit_time` not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`audit_time` between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`audit_time` not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditNameIsNull() {
            addCriterion("`audit_name` is null");
            return (Criteria) this;
        }

        public Criteria andAuditNameIsNotNull() {
            addCriterion("`audit_name` is not null");
            return (Criteria) this;
        }

        public Criteria andAuditNameEqualTo(String value) {
            addCriterion("`audit_name` =", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotEqualTo(String value) {
            addCriterion("`audit_name` <>", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameGreaterThan(String value) {
            addCriterion("`audit_name` >", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameGreaterThanOrEqualTo(String value) {
            addCriterion("`audit_name` >=", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameLessThan(String value) {
            addCriterion("`audit_name` <", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameLessThanOrEqualTo(String value) {
            addCriterion("`audit_name` <=", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameLike(String value) {
            addCriterion("`audit_name` like", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotLike(String value) {
            addCriterion("`audit_name` not like", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameIn(List<String> values) {
            addCriterion("`audit_name` in", values, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotIn(List<String> values) {
            addCriterion("`audit_name` not in", values, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameBetween(String value1, String value2) {
            addCriterion("`audit_name` between", value1, value2, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotBetween(String value1, String value2) {
            addCriterion("`audit_name` not between", value1, value2, "auditName");
            return (Criteria) this;
        }

        public Criteria andProhibitByIsNull() {
            addCriterion("`prohibit_by` is null");
            return (Criteria) this;
        }

        public Criteria andProhibitByIsNotNull() {
            addCriterion("`prohibit_by` is not null");
            return (Criteria) this;
        }

        public Criteria andProhibitByEqualTo(Long value) {
            addCriterion("`prohibit_by` =", value, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByNotEqualTo(Long value) {
            addCriterion("`prohibit_by` <>", value, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByGreaterThan(Long value) {
            addCriterion("`prohibit_by` >", value, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByGreaterThanOrEqualTo(Long value) {
            addCriterion("`prohibit_by` >=", value, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByLessThan(Long value) {
            addCriterion("`prohibit_by` <", value, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByLessThanOrEqualTo(Long value) {
            addCriterion("`prohibit_by` <=", value, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByIn(List<Long> values) {
            addCriterion("`prohibit_by` in", values, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByNotIn(List<Long> values) {
            addCriterion("`prohibit_by` not in", values, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByBetween(Long value1, Long value2) {
            addCriterion("`prohibit_by` between", value1, value2, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitByNotBetween(Long value1, Long value2) {
            addCriterion("`prohibit_by` not between", value1, value2, "prohibitBy");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeIsNull() {
            addCriterion("`prohibit_time` is null");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeIsNotNull() {
            addCriterion("`prohibit_time` is not null");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeEqualTo(LocalDateTime value) {
            addCriterion("`prohibit_time` =", value, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`prohibit_time` <>", value, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeGreaterThan(LocalDateTime value) {
            addCriterion("`prohibit_time` >", value, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`prohibit_time` >=", value, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeLessThan(LocalDateTime value) {
            addCriterion("`prohibit_time` <", value, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`prohibit_time` <=", value, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeIn(List<LocalDateTime> values) {
            addCriterion("`prohibit_time` in", values, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`prohibit_time` not in", values, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`prohibit_time` between", value1, value2, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`prohibit_time` not between", value1, value2, "prohibitTime");
            return (Criteria) this;
        }

        public Criteria andProhibitNameIsNull() {
            addCriterion("`prohibit_name` is null");
            return (Criteria) this;
        }

        public Criteria andProhibitNameIsNotNull() {
            addCriterion("`prohibit_name` is not null");
            return (Criteria) this;
        }

        public Criteria andProhibitNameEqualTo(String value) {
            addCriterion("`prohibit_name` =", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameNotEqualTo(String value) {
            addCriterion("`prohibit_name` <>", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameGreaterThan(String value) {
            addCriterion("`prohibit_name` >", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameGreaterThanOrEqualTo(String value) {
            addCriterion("`prohibit_name` >=", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameLessThan(String value) {
            addCriterion("`prohibit_name` <", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameLessThanOrEqualTo(String value) {
            addCriterion("`prohibit_name` <=", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameLike(String value) {
            addCriterion("`prohibit_name` like", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameNotLike(String value) {
            addCriterion("`prohibit_name` not like", value, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameIn(List<String> values) {
            addCriterion("`prohibit_name` in", values, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameNotIn(List<String> values) {
            addCriterion("`prohibit_name` not in", values, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameBetween(String value1, String value2) {
            addCriterion("`prohibit_name` between", value1, value2, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andProhibitNameNotBetween(String value1, String value2) {
            addCriterion("`prohibit_name` not between", value1, value2, "prohibitName");
            return (Criteria) this;
        }

        public Criteria andAllowedByIsNull() {
            addCriterion("`allowed_by` is null");
            return (Criteria) this;
        }

        public Criteria andAllowedByIsNotNull() {
            addCriterion("`allowed_by` is not null");
            return (Criteria) this;
        }

        public Criteria andAllowedByEqualTo(Long value) {
            addCriterion("`allowed_by` =", value, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByNotEqualTo(Long value) {
            addCriterion("`allowed_by` <>", value, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByGreaterThan(Long value) {
            addCriterion("`allowed_by` >", value, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByGreaterThanOrEqualTo(Long value) {
            addCriterion("`allowed_by` >=", value, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByLessThan(Long value) {
            addCriterion("`allowed_by` <", value, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByLessThanOrEqualTo(Long value) {
            addCriterion("`allowed_by` <=", value, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByIn(List<Long> values) {
            addCriterion("`allowed_by` in", values, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByNotIn(List<Long> values) {
            addCriterion("`allowed_by` not in", values, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByBetween(Long value1, Long value2) {
            addCriterion("`allowed_by` between", value1, value2, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowedByNotBetween(Long value1, Long value2) {
            addCriterion("`allowed_by` not between", value1, value2, "allowedBy");
            return (Criteria) this;
        }

        public Criteria andAllowTimeIsNull() {
            addCriterion("`allow_time` is null");
            return (Criteria) this;
        }

        public Criteria andAllowTimeIsNotNull() {
            addCriterion("`allow_time` is not null");
            return (Criteria) this;
        }

        public Criteria andAllowTimeEqualTo(LocalDateTime value) {
            addCriterion("`allow_time` =", value, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`allow_time` <>", value, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeGreaterThan(LocalDateTime value) {
            addCriterion("`allow_time` >", value, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`allow_time` >=", value, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeLessThan(LocalDateTime value) {
            addCriterion("`allow_time` <", value, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`allow_time` <=", value, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeIn(List<LocalDateTime> values) {
            addCriterion("`allow_time` in", values, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`allow_time` not in", values, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`allow_time` between", value1, value2, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`allow_time` not between", value1, value2, "allowTime");
            return (Criteria) this;
        }

        public Criteria andAllowNameIsNull() {
            addCriterion("`allow_name` is null");
            return (Criteria) this;
        }

        public Criteria andAllowNameIsNotNull() {
            addCriterion("`allow_name` is not null");
            return (Criteria) this;
        }

        public Criteria andAllowNameEqualTo(String value) {
            addCriterion("`allow_name` =", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameNotEqualTo(String value) {
            addCriterion("`allow_name` <>", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameGreaterThan(String value) {
            addCriterion("`allow_name` >", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameGreaterThanOrEqualTo(String value) {
            addCriterion("`allow_name` >=", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameLessThan(String value) {
            addCriterion("`allow_name` <", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameLessThanOrEqualTo(String value) {
            addCriterion("`allow_name` <=", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameLike(String value) {
            addCriterion("`allow_name` like", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameNotLike(String value) {
            addCriterion("`allow_name` not like", value, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameIn(List<String> values) {
            addCriterion("`allow_name` in", values, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameNotIn(List<String> values) {
            addCriterion("`allow_name` not in", values, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameBetween(String value1, String value2) {
            addCriterion("`allow_name` between", value1, value2, "allowName");
            return (Criteria) this;
        }

        public Criteria andAllowNameNotBetween(String value1, String value2) {
            addCriterion("`allow_name` not between", value1, value2, "allowName");
            return (Criteria) this;
        }

        public Criteria andOnshelfByIsNull() {
            addCriterion("`onshelf_by` is null");
            return (Criteria) this;
        }

        public Criteria andOnshelfByIsNotNull() {
            addCriterion("`onshelf_by` is not null");
            return (Criteria) this;
        }

        public Criteria andOnshelfByEqualTo(Long value) {
            addCriterion("`onshelf_by` =", value, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByNotEqualTo(Long value) {
            addCriterion("`onshelf_by` <>", value, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByGreaterThan(Long value) {
            addCriterion("`onshelf_by` >", value, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByGreaterThanOrEqualTo(Long value) {
            addCriterion("`onshelf_by` >=", value, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByLessThan(Long value) {
            addCriterion("`onshelf_by` <", value, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByLessThanOrEqualTo(Long value) {
            addCriterion("`onshelf_by` <=", value, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByIn(List<Long> values) {
            addCriterion("`onshelf_by` in", values, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByNotIn(List<Long> values) {
            addCriterion("`onshelf_by` not in", values, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByBetween(Long value1, Long value2) {
            addCriterion("`onshelf_by` between", value1, value2, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfByNotBetween(Long value1, Long value2) {
            addCriterion("`onshelf_by` not between", value1, value2, "onshelfBy");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeIsNull() {
            addCriterion("`onshelf_time` is null");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeIsNotNull() {
            addCriterion("`onshelf_time` is not null");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeEqualTo(LocalDateTime value) {
            addCriterion("`onshelf_time` =", value, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`onshelf_time` <>", value, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeGreaterThan(LocalDateTime value) {
            addCriterion("`onshelf_time` >", value, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`onshelf_time` >=", value, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeLessThan(LocalDateTime value) {
            addCriterion("`onshelf_time` <", value, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`onshelf_time` <=", value, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeIn(List<LocalDateTime> values) {
            addCriterion("`onshelf_time` in", values, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`onshelf_time` not in", values, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`onshelf_time` between", value1, value2, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`onshelf_time` not between", value1, value2, "onshelfTime");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameIsNull() {
            addCriterion("`onshelf_name` is null");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameIsNotNull() {
            addCriterion("`onshelf_name` is not null");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameEqualTo(String value) {
            addCriterion("`onshelf_name` =", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameNotEqualTo(String value) {
            addCriterion("`onshelf_name` <>", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameGreaterThan(String value) {
            addCriterion("`onshelf_name` >", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameGreaterThanOrEqualTo(String value) {
            addCriterion("`onshelf_name` >=", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameLessThan(String value) {
            addCriterion("`onshelf_name` <", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameLessThanOrEqualTo(String value) {
            addCriterion("`onshelf_name` <=", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameLike(String value) {
            addCriterion("`onshelf_name` like", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameNotLike(String value) {
            addCriterion("`onshelf_name` not like", value, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameIn(List<String> values) {
            addCriterion("`onshelf_name` in", values, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameNotIn(List<String> values) {
            addCriterion("`onshelf_name` not in", values, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameBetween(String value1, String value2) {
            addCriterion("`onshelf_name` between", value1, value2, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOnshelfNameNotBetween(String value1, String value2) {
            addCriterion("`onshelf_name` not between", value1, value2, "onshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfByIsNull() {
            addCriterion("`offshelf_by` is null");
            return (Criteria) this;
        }

        public Criteria andOffshelfByIsNotNull() {
            addCriterion("`offshelf_by` is not null");
            return (Criteria) this;
        }

        public Criteria andOffshelfByEqualTo(Long value) {
            addCriterion("`offshelf_by` =", value, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByNotEqualTo(Long value) {
            addCriterion("`offshelf_by` <>", value, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByGreaterThan(Long value) {
            addCriterion("`offshelf_by` >", value, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByGreaterThanOrEqualTo(Long value) {
            addCriterion("`offshelf_by` >=", value, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByLessThan(Long value) {
            addCriterion("`offshelf_by` <", value, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByLessThanOrEqualTo(Long value) {
            addCriterion("`offshelf_by` <=", value, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByIn(List<Long> values) {
            addCriterion("`offshelf_by` in", values, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByNotIn(List<Long> values) {
            addCriterion("`offshelf_by` not in", values, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByBetween(Long value1, Long value2) {
            addCriterion("`offshelf_by` between", value1, value2, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfByNotBetween(Long value1, Long value2) {
            addCriterion("`offshelf_by` not between", value1, value2, "offshelfBy");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeIsNull() {
            addCriterion("`offshelf_time` is null");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeIsNotNull() {
            addCriterion("`offshelf_time` is not null");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeEqualTo(LocalDateTime value) {
            addCriterion("`offshelf_time` =", value, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`offshelf_time` <>", value, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeGreaterThan(LocalDateTime value) {
            addCriterion("`offshelf_time` >", value, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`offshelf_time` >=", value, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeLessThan(LocalDateTime value) {
            addCriterion("`offshelf_time` <", value, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`offshelf_time` <=", value, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeIn(List<LocalDateTime> values) {
            addCriterion("`offshelf_time` in", values, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`offshelf_time` not in", values, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`offshelf_time` between", value1, value2, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`offshelf_time` not between", value1, value2, "offshelfTime");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameIsNull() {
            addCriterion("`offshelf_name` is null");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameIsNotNull() {
            addCriterion("`offshelf_name` is not null");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameEqualTo(String value) {
            addCriterion("`offshelf_name` =", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameNotEqualTo(String value) {
            addCriterion("`offshelf_name` <>", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameGreaterThan(String value) {
            addCriterion("`offshelf_name` >", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameGreaterThanOrEqualTo(String value) {
            addCriterion("`offshelf_name` >=", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameLessThan(String value) {
            addCriterion("`offshelf_name` <", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameLessThanOrEqualTo(String value) {
            addCriterion("`offshelf_name` <=", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameLike(String value) {
            addCriterion("`offshelf_name` like", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameNotLike(String value) {
            addCriterion("`offshelf_name` not like", value, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameIn(List<String> values) {
            addCriterion("`offshelf_name` in", values, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameNotIn(List<String> values) {
            addCriterion("`offshelf_name` not in", values, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameBetween(String value1, String value2) {
            addCriterion("`offshelf_name` between", value1, value2, "offshelfName");
            return (Criteria) this;
        }

        public Criteria andOffshelfNameNotBetween(String value1, String value2) {
            addCriterion("`offshelf_name` not between", value1, value2, "offshelfName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_product
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oomall_product
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}