package cn.edu.xmu.oomall.goods.model.po;

import java.time.LocalDateTime;

public class ProductPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.freight_id
     *
     * @mbg.generated
     */
    private Long freightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.sku_sn
     *
     * @mbg.generated
     */
    private String skuSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.original_price
     *
     * @mbg.generated
     */
    private Long originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.weight
     *
     * @mbg.generated
     */
    private Long weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.barcode
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.origin_place
     *
     * @mbg.generated
     */
    private String originPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.audited_by
     *
     * @mbg.generated
     */
    private Long auditedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.audit_time
     *
     * @mbg.generated
     */
    private LocalDateTime auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.audit_name
     *
     * @mbg.generated
     */
    private String auditName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.prohibit_by
     *
     * @mbg.generated
     */
    private Long prohibitBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.prohibit_time
     *
     * @mbg.generated
     */
    private LocalDateTime prohibitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.prohibit_name
     *
     * @mbg.generated
     */
    private String prohibitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.allowed_by
     *
     * @mbg.generated
     */
    private Long allowedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.allow_time
     *
     * @mbg.generated
     */
    private LocalDateTime allowTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.allow_name
     *
     * @mbg.generated
     */
    private String allowName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.onshelf_by
     *
     * @mbg.generated
     */
    private Long onshelfBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.onshelf_time
     *
     * @mbg.generated
     */
    private LocalDateTime onshelfTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.onshelf_name
     *
     * @mbg.generated
     */
    private String onshelfName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.offshelf_by
     *
     * @mbg.generated
     */
    private Long offshelfBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.offshelf_time
     *
     * @mbg.generated
     */
    private LocalDateTime offshelfTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_product.offshelf_name
     *
     * @mbg.generated
     */
    private String offshelfName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.id
     *
     * @return the value of oomall_product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.id
     *
     * @param id the value for oomall_product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.shop_id
     *
     * @return the value of oomall_product.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.shop_id
     *
     * @param shopId the value for oomall_product.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.shop_name
     *
     * @return the value of oomall_product.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.shop_name
     *
     * @param shopName the value for oomall_product.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.goods_id
     *
     * @return the value of oomall_product.goods_id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.goods_id
     *
     * @param goodsId the value for oomall_product.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.category_id
     *
     * @return the value of oomall_product.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.category_id
     *
     * @param categoryId the value for oomall_product.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.freight_id
     *
     * @return the value of oomall_product.freight_id
     *
     * @mbg.generated
     */
    public Long getFreightId() {
        return freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.freight_id
     *
     * @param freightId the value for oomall_product.freight_id
     *
     * @mbg.generated
     */
    public void setFreightId(Long freightId) {
        this.freightId = freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.sku_sn
     *
     * @return the value of oomall_product.sku_sn
     *
     * @mbg.generated
     */
    public String getSkuSn() {
        return skuSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.sku_sn
     *
     * @param skuSn the value for oomall_product.sku_sn
     *
     * @mbg.generated
     */
    public void setSkuSn(String skuSn) {
        this.skuSn = skuSn == null ? null : skuSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.name
     *
     * @return the value of oomall_product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.name
     *
     * @param name the value for oomall_product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.original_price
     *
     * @return the value of oomall_product.original_price
     *
     * @mbg.generated
     */
    public Long getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.original_price
     *
     * @param originalPrice the value for oomall_product.original_price
     *
     * @mbg.generated
     */
    public void setOriginalPrice(Long originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.weight
     *
     * @return the value of oomall_product.weight
     *
     * @mbg.generated
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.weight
     *
     * @param weight the value for oomall_product.weight
     *
     * @mbg.generated
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.image_url
     *
     * @return the value of oomall_product.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.image_url
     *
     * @param imageUrl the value for oomall_product.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.barcode
     *
     * @return the value of oomall_product.barcode
     *
     * @mbg.generated
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.barcode
     *
     * @param barcode the value for oomall_product.barcode
     *
     * @mbg.generated
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.unit
     *
     * @return the value of oomall_product.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.unit
     *
     * @param unit the value for oomall_product.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.origin_place
     *
     * @return the value of oomall_product.origin_place
     *
     * @mbg.generated
     */
    public String getOriginPlace() {
        return originPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.origin_place
     *
     * @param originPlace the value for oomall_product.origin_place
     *
     * @mbg.generated
     */
    public void setOriginPlace(String originPlace) {
        this.originPlace = originPlace == null ? null : originPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.create_name
     *
     * @return the value of oomall_product.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.create_name
     *
     * @param createName the value for oomall_product.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.create_time
     *
     * @return the value of oomall_product.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.create_time
     *
     * @param createTime the value for oomall_product.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.audited_by
     *
     * @return the value of oomall_product.audited_by
     *
     * @mbg.generated
     */
    public Long getAuditedBy() {
        return auditedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.audited_by
     *
     * @param auditedBy the value for oomall_product.audited_by
     *
     * @mbg.generated
     */
    public void setAuditedBy(Long auditedBy) {
        this.auditedBy = auditedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.audit_time
     *
     * @return the value of oomall_product.audit_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.audit_time
     *
     * @param auditTime the value for oomall_product.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(LocalDateTime auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.audit_name
     *
     * @return the value of oomall_product.audit_name
     *
     * @mbg.generated
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.audit_name
     *
     * @param auditName the value for oomall_product.audit_name
     *
     * @mbg.generated
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName == null ? null : auditName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.prohibit_by
     *
     * @return the value of oomall_product.prohibit_by
     *
     * @mbg.generated
     */
    public Long getProhibitBy() {
        return prohibitBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.prohibit_by
     *
     * @param prohibitBy the value for oomall_product.prohibit_by
     *
     * @mbg.generated
     */
    public void setProhibitBy(Long prohibitBy) {
        this.prohibitBy = prohibitBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.prohibit_time
     *
     * @return the value of oomall_product.prohibit_time
     *
     * @mbg.generated
     */
    public LocalDateTime getProhibitTime() {
        return prohibitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.prohibit_time
     *
     * @param prohibitTime the value for oomall_product.prohibit_time
     *
     * @mbg.generated
     */
    public void setProhibitTime(LocalDateTime prohibitTime) {
        this.prohibitTime = prohibitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.prohibit_name
     *
     * @return the value of oomall_product.prohibit_name
     *
     * @mbg.generated
     */
    public String getProhibitName() {
        return prohibitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.prohibit_name
     *
     * @param prohibitName the value for oomall_product.prohibit_name
     *
     * @mbg.generated
     */
    public void setProhibitName(String prohibitName) {
        this.prohibitName = prohibitName == null ? null : prohibitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.allowed_by
     *
     * @return the value of oomall_product.allowed_by
     *
     * @mbg.generated
     */
    public Long getAllowedBy() {
        return allowedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.allowed_by
     *
     * @param allowedBy the value for oomall_product.allowed_by
     *
     * @mbg.generated
     */
    public void setAllowedBy(Long allowedBy) {
        this.allowedBy = allowedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.allow_time
     *
     * @return the value of oomall_product.allow_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAllowTime() {
        return allowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.allow_time
     *
     * @param allowTime the value for oomall_product.allow_time
     *
     * @mbg.generated
     */
    public void setAllowTime(LocalDateTime allowTime) {
        this.allowTime = allowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.allow_name
     *
     * @return the value of oomall_product.allow_name
     *
     * @mbg.generated
     */
    public String getAllowName() {
        return allowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.allow_name
     *
     * @param allowName the value for oomall_product.allow_name
     *
     * @mbg.generated
     */
    public void setAllowName(String allowName) {
        this.allowName = allowName == null ? null : allowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.onshelf_by
     *
     * @return the value of oomall_product.onshelf_by
     *
     * @mbg.generated
     */
    public Long getOnshelfBy() {
        return onshelfBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.onshelf_by
     *
     * @param onshelfBy the value for oomall_product.onshelf_by
     *
     * @mbg.generated
     */
    public void setOnshelfBy(Long onshelfBy) {
        this.onshelfBy = onshelfBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.onshelf_time
     *
     * @return the value of oomall_product.onshelf_time
     *
     * @mbg.generated
     */
    public LocalDateTime getOnshelfTime() {
        return onshelfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.onshelf_time
     *
     * @param onshelfTime the value for oomall_product.onshelf_time
     *
     * @mbg.generated
     */
    public void setOnshelfTime(LocalDateTime onshelfTime) {
        this.onshelfTime = onshelfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.onshelf_name
     *
     * @return the value of oomall_product.onshelf_name
     *
     * @mbg.generated
     */
    public String getOnshelfName() {
        return onshelfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.onshelf_name
     *
     * @param onshelfName the value for oomall_product.onshelf_name
     *
     * @mbg.generated
     */
    public void setOnshelfName(String onshelfName) {
        this.onshelfName = onshelfName == null ? null : onshelfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.offshelf_by
     *
     * @return the value of oomall_product.offshelf_by
     *
     * @mbg.generated
     */
    public Long getOffshelfBy() {
        return offshelfBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.offshelf_by
     *
     * @param offshelfBy the value for oomall_product.offshelf_by
     *
     * @mbg.generated
     */
    public void setOffshelfBy(Long offshelfBy) {
        this.offshelfBy = offshelfBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.offshelf_time
     *
     * @return the value of oomall_product.offshelf_time
     *
     * @mbg.generated
     */
    public LocalDateTime getOffshelfTime() {
        return offshelfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.offshelf_time
     *
     * @param offshelfTime the value for oomall_product.offshelf_time
     *
     * @mbg.generated
     */
    public void setOffshelfTime(LocalDateTime offshelfTime) {
        this.offshelfTime = offshelfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_product.offshelf_name
     *
     * @return the value of oomall_product.offshelf_name
     *
     * @mbg.generated
     */
    public String getOffshelfName() {
        return offshelfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_product.offshelf_name
     *
     * @param offshelfName the value for oomall_product.offshelf_name
     *
     * @mbg.generated
     */
    public void setOffshelfName(String offshelfName) {
        this.offshelfName = offshelfName == null ? null : offshelfName.trim();
    }
}