package cn.edu.xmu.oomall.freight.mapper;

import cn.edu.xmu.oomall.goods.model.po.PieceFreightPo;
import cn.edu.xmu.oomall.goods.model.po.PieceFreightPoExample;
import java.util.List;

public interface PieceFreightPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_piece_freight
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_piece_freight
     *
     * @mbg.generated
     */
    int insert(PieceFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_piece_freight
     *
     * @mbg.generated
     */
    int insertSelective(PieceFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_piece_freight
     *
     * @mbg.generated
     */
    List<PieceFreightPo> selectByExample(PieceFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_piece_freight
     *
     * @mbg.generated
     */
    PieceFreightPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_piece_freight
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PieceFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_piece_freight
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PieceFreightPo record);
}