package cn.edu.xmu.oomall.coupon.mapper;

import cn.edu.xmu.oomall.coupon.model.po.CouponOnsalePo;
import cn.edu.xmu.oomall.coupon.model.po.CouponOnsalePoExample;
import java.util.List;

public interface CouponOnsalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_coupon_onsale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_coupon_onsale
     *
     * @mbg.generated
     */
    int insert(CouponOnsalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_coupon_onsale
     *
     * @mbg.generated
     */
    int insertSelective(CouponOnsalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_coupon_onsale
     *
     * @mbg.generated
     */
    List<CouponOnsalePo> selectByExample(CouponOnsalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_coupon_onsale
     *
     * @mbg.generated
     */
    CouponOnsalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_coupon_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponOnsalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_coupon_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponOnsalePo record);
}