package cn.edu.xmu.oomall.activity.mapper;

import cn.edu.xmu.oomall.activity.model.po.AdvanceSalePo;
import cn.edu.xmu.oomall.activity.model.po.AdvanceSalePoExample;
import java.util.List;

public interface AdvanceSalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_advance_sale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_advance_sale
     *
     * @mbg.generated
     */
    int insert(AdvanceSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_advance_sale
     *
     * @mbg.generated
     */
    int insertSelective(AdvanceSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_advance_sale
     *
     * @mbg.generated
     */
    List<AdvanceSalePo> selectByExample(AdvanceSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_advance_sale
     *
     * @mbg.generated
     */
    AdvanceSalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_advance_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdvanceSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_advance_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdvanceSalePo record);
}