package cn.edu.xmu.oomall.activity.mapper;

import cn.edu.xmu.oomall.activity.model.po.GroupOnActivityPo;
import cn.edu.xmu.oomall.activity.model.po.GroupOnActivityPoExample;
import java.util.List;

public interface GroupOnActivityPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_groupon_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_groupon_activity
     *
     * @mbg.generated
     */
    int insert(GroupOnActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_groupon_activity
     *
     * @mbg.generated
     */
    int insertSelective(GroupOnActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_groupon_activity
     *
     * @mbg.generated
     */
    List<GroupOnActivityPo> selectByExample(GroupOnActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_groupon_activity
     *
     * @mbg.generated
     */
    GroupOnActivityPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupOnActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupOnActivityPo record);
}