package cn.edu.xmu.oomall.activity.mapper;

import cn.edu.xmu.oomall.activity.model.po.ShareActivityPo;
import cn.edu.xmu.oomall.activity.model.po.ShareActivityPoExample;
import java.util.List;

public interface ShareActivityPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share_activity
     *
     * @mbg.generated
     */
    int insert(ShareActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share_activity
     *
     * @mbg.generated
     */
    int insertSelective(ShareActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share_activity
     *
     * @mbg.generated
     */
    List<ShareActivityPo> selectByExample(ShareActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share_activity
     *
     * @mbg.generated
     */
    ShareActivityPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareActivityPo record);
}